Support for v1beta1 PluginInterface GetDevicePluginOptions
kubevirt/device-plugin-manager pull request #15
Opened 2021-07-15 12:57 UTC by mderoy

Request should be registered with options obtained from GetDevicePluginOptions. this allows you to specify PreStartRequired:true and other options from your device plugin

[root@mysystem]# oc logs pod/mypod | grep GetDev
I0715 12:53:48.737962       1 main.go:104] GetDevicePluginOptions
I0715 12:53:48.738040       1 main.go:104] GetDevicePluginOptions
I0715 12:53:48.738086       1 main.go:104] GetDevicePluginOptions
[root@mysystem]# oc logs pod/mypod | grep PreSt
I0715 12:54:03.380576       1 main.go:139] PreStartContainer: mydevice1
I0715 12:54:03.380863       1 main.go:139] PreStartContainer: mydevice2
I0715 12:54:03.381066       1 main.go:139] PreStartContainer: mydevice3

2021-07-15 14:03 UTC, phoracek commented
/assign @phoracek

2021-07-16 08:01 UTC, phoracek requested changes
Small nit, overall it looks good

2021-07-16 08:01 UTC, phoracek commented on pkg/dpm/plugin.go
> +		Options: options,
Please run `go fmt` on this file.

2021-07-16 12:38 UTC, mderoy commented on pkg/dpm/plugin.go
> +		Options: options,
go fmt run and squashed into commit.

2021-07-16 14:54 UTC, phoracek approved these changes
Looks good, thanks!

2021-07-16 14:54 UTC, merged